"""empty message

Revision ID: 0e943b382efa
Revises: 7a6672811a01
Create Date: 2019-03-06 14:55:34.288359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e943b382efa'
down_revision = '7a6672811a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.add_column('companies', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('stock_price', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_companies_stock_price'), 'companies', ['stock_price'], unique=False)
    op.drop_index('ix_companies_latest_price', table_name='companies')
    op.create_foreign_key(None, 'companies', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_column('companies', 'latest_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('latest_price', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_index('ix_companies_latest_price', 'companies', ['latest_price'], unique=False)
    op.drop_index(op.f('ix_companies_stock_price'), table_name='companies')
    op.drop_column('companies', 'stock_price')
    op.drop_column('companies', 'portfolio_id')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
