"""empty message

Revision ID: 5d656ab23409
Revises: 0e943b382efa
Create Date: 2019-03-06 16:25:53.800803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d656ab23409'
down_revision = '0e943b382efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(length=256), nullable=True))
    op.add_column('companies', sa.Column('sector', sa.String(length=256), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=True)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=True)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=True)
    op.drop_index('ix_companies_stock_price', table_name='companies')
    op.drop_column('companies', 'stock_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stock_price', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_companies_stock_price', 'companies', ['stock_price'], unique=False)
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'sector')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
