"""initial migration

Revision ID: 7a6672811a01
Revises: 
Create Date: 2019-03-01 14:19:38.265525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6672811a01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('company_sym', sa.String(length=256), nullable=True),
    sa.Column('latest_price', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_sym'), 'companies', ['company_sym'], unique=True)
    op.create_index(op.f('ix_companies_latest_price'), 'companies', ['latest_price'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_latest_price'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_sym'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
