"""empty message

Revision ID: 9f483f80f6e6
Revises: 5d656ab23409
Create Date: 2019-03-06 16:59:36.986142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f483f80f6e6'
down_revision = '5d656ab23409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_name'), 'portfolio', ['name'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('company_sym', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('sector', sa.String(length=256), nullable=True),
    sa.Column('industry', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_sym'), 'company', ['company_sym'], unique=True)
    op.create_index(op.f('ix_company_industry'), 'company', ['industry'], unique=True)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_sector'), 'company', ['sector'], unique=True)
    op.create_index(op.f('ix_company_website'), 'company', ['website'], unique=True)
    op.drop_index('ix_companies_company_sym', table_name='companies')
    op.drop_index('ix_companies_industry', table_name='companies')
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_index('ix_companies_sector', table_name='companies')
    op.drop_index('ix_companies_website', table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_portfolios_name', table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('portfolios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_portfolios_name', 'portfolios', ['name'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('company_sym', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='companies_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    op.create_index('ix_companies_website', 'companies', ['website'], unique=True)
    op.create_index('ix_companies_sector', 'companies', ['sector'], unique=True)
    op.create_index('ix_companies_name', 'companies', ['name'], unique=True)
    op.create_index('ix_companies_industry', 'companies', ['industry'], unique=True)
    op.create_index('ix_companies_company_sym', 'companies', ['company_sym'], unique=True)
    op.drop_index(op.f('ix_company_website'), table_name='company')
    op.drop_index(op.f('ix_company_sector'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_industry'), table_name='company')
    op.drop_index(op.f('ix_company_company_sym'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_portfolio_name'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
